let guest2 = ["samrah","maria","ali","hasnain","rukhsana","riaz","mujtaba","tooba"]
console.log("the following list of guest invited to the dinner are as follows:-")
console.log(guest2)
guest2.pop()
console.log(guest2)
console.log("i am really sorry tooba i cant invite you to the dinner")
guest2.pop()
console.log(guest2)
console.log("i am really sorry mujtaba i cant invite you to the dinner")
guest2.pop()
console.log(guest2)
console.log("i am really sorry riaz i cant invite u to the dinner")
guest2.pop()
console.log(guest2)
console.log("i am really sorry rukhsana i cant invite u to the dinner")
guest2.pop()
console.log(guest2)
console.log("i am really sorry hasnain i cant invite u to the dinner")
guest2.pop()
console.log(guest2)
console.log("i am really sorry ali i cant invite you to the dinner")
console.log(`"the persons which i can invite them at dinner are"`)
console.log(guest2)
