"use strict";
let a = 2;
let b = 4;
let c = 6;
let d = 10;
let e = 16;
let mul = a * b;
console.log(`multiplication of two numbers is ${mul}`);
let add = a + c;
console.log(`addition of two numbers is ${add}`);
let sub = d - a;
console.log(`subtraction of two numbers is ${sub}`);
let div = e / a;
console.log(`division of two numbers is ${div}`);
